"""empty message

Revision ID: 0f0bd1e9444e
Revises:
Create Date: 2018-03-26 14:56:14.409203

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '0f0bd1e9444e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('match', sa.Column('has_unexpected_third_game', sa.Boolean(), nullable=True))
    op.add_column('match', sa.Column('is_league', sa.Boolean(), nullable=True))
    op.add_column('match', sa.Column('is_tournament', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('match', 'is_tournament')
    op.drop_column('match', 'is_league')
    op.drop_column('match', 'has_unexpected_third_game')
    # ### end Alembic commands ###
