"""empty message

Revision ID: 4680022c11c2
Revises: 0f0bd1e9444e
Create Date: 2018-03-27 21:37:09.497103

"""

from alembic import op

# revision identifiers, used by Alembic.
revision = '4680022c11c2'
down_revision = '0f0bd1e9444e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_tournament_name'), 'tournament', ['name'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tournament_name'), table_name='tournament')
    # ### end Alembic commands ###
