monolith:
  - changed-files:
    - any-glob-to-any-file:
      - ./*

decks:
  - changed-files:
    - any-glob-to-any-file:
      - ./decksite/*
      - ./decksite/**/*

logsite:
  - changed-files:
    - any-glob-to-any-file:
      - ./logsite/*
      - ./logsite/**/*

discord bot:
  - changed-files:
    - any-glob-to-any-file:
      - ./discordbot/*
      - ./discordbot/**/*

magic:
  - changed-files:
    - any-glob-to-any-file:
      - ./magic/*
      - ./magic/**/*

shared:
  - changed-files:
    - any-glob-to-any-file:
      - ./shared/*
      - ./shared/**/*
      - ./shared_web/*
      - ./shared_web/**/*

prices:
  - changed-files:
    - any-glob-to-any-file:
      - ./price_grabber/*
      - ./price_grabber/**/*

rotation:
  - changed-files:
    - any-glob-to-any-file:
      - ./rotation/*
      - ./rotation/**/*

maintenance:
  - changed-files:
    - any-glob-to-any-file:
      - ./maintenance/*
      - ./maintenance/**/*

tests:
  - changed-files:
    - any-glob-to-any-file:
      - ./**/*_test.py
