queue_rules:
  - name: duplicated default from automatic merge for master when CI passes and approved
    queue_conditions:
      - "#approved-reviews-by>=1"
      - "#review-requested=0"
      - "#changes-requested-reviews-by=0"
      - "#commented-reviews-by=0"
      - status-success=mypy
      - status-success=lint
      - status-success=test
      - status-success=jslint
      - base=master
    merge_conditions:
      # Conditions to get out of the queue (= merged)
      - status-success=mypy
      - status-success=lint
      - status-success=test
      - status-success=jslint
    merge_method: rebase
  - name: trusted
    queue_conditions:
      - author=@PennyDreadfulMTG/automerge
      - base=master
    merge_conditions:
      # Conditions to get out of the queue (= merged)
      - author=@PennyDreadfulMTG/automerge
      - status-success=mypy
      - status-success=lint
      - status-success=test
      - status-success=jslint
    merge_method: merge
  - name: default
    merge_conditions:
      # Conditions to get out of the queue (= merged)
      - status-success=mypy
      - status-success=lint
      - status-success=test
      - status-success=jslint

pull_request_rules:
  - name: automatic merge dependency updates
    conditions:
      - status-success=mypy
      - status-success=lint
      - status-success=test
      - status-success=jslint
      - author~=(pyup-bot|dependabot)
      - -files~=^(!?.github/workflows/)
    actions:
      merge:
        method: rebase
      delete_head_branch: {}
  - name: automatic merge for master when CI passes and approved + automatic merge
      for master when CI passes and trusted comitter
    conditions:
        - author=@PennyDreadfulMTG/automerge
    actions:
      queue:
