pull_request_rules:
  - name: automatic merge dependency updates
    conditions:
      - status-success=pdm/automerge
      - status-success=Travis CI - Pull Request
      - author~=(pyup-bot|dependabot)
      - -files~=^(!?.github/workflows/)
    actions:
      merge:
        method: rebase
      delete_head_branch: {}
  - name: automatic merge for master when CI passes and approved
    conditions:
      - "#approved-reviews-by>=1"
      - "#review-requested=0"
      - "#changes-requested-reviews-by=0"
      - "#commented-reviews-by=0"
      - status-success=Travis CI - Pull Request
      - base=master
    actions:
      merge:
        method: rebase
        strict: true
  - name: automatic merge for master when CI passes and trusted comitter
    conditions:
      - author=@PennyDreadfulMTG/automerge
      - status-success=Travis CI - Pull Request
      - base=master
    actions:
      merge:
        method: merge
        strict: true
