from .about import About
from .about_pdm import AboutPdm
from .achievements import Achievements
from .add_form import AddForm
from .admin import Admin
from .admin_retire import AdminRetire
from .archetype import Archetype
from .archetypes import Archetypes
from .bugs import Bugs
from .card import Card
from .cards import Cards
from .community_guidelines import CommunityGuidelines
from .competition import Competition
from .competitions import Competitions
from .deck import Deck, DeckEmbed
from .deck_check import DeckCheck
from .decks import Decks
from .edit_aliases import EditAliases
from .edit_archetypes import EditArchetypes
from .edit_league import EditLeague
from .edit_matches import EditMatches
from .edit_news import EditNews
from .edit_rules import EditRules
from .faqs import Faqs
from .home import Home
from .kickoff import KickOff
from .league_form import LeagueForm
from .league_info import LeagueInfo
from .link_accounts import LinkAccounts
from .matchups import Matchups
from .pd500 import PD500
from .people import People
from .person import Person
from .person_achievements import PersonAchievements
from .person_matches import PersonMatches
from .player_notes import PlayerNotes
from .prizes import Prizes
from .report import Report
from .resources import Resources
from .retire import Retire
from .rotation import Rotation
from .rotation_changes import RotationChanges
from .rotation_checklist import RotationChecklist
from .seasons import Seasons
from .signup import SignUp
from .tournament_hosting import TournamentHosting
from .tournament_leaderboards import TournamentLeaderboards
from .tournaments import Tournaments
from .unlink import Unlink
