ALTER TABLE competition ADD COLUMN top_n INTEGER;

UPDATE competition SET top_n = 8; -- Default to Top 8

-- Now correct the other cases.

-- Top 4s
UPDATE competition SET top_n = 4 WHERE url IN ('https://gatherling.one/eventreport.php?event=APAC Penny Dreadful Sundays 7.02', 'https://gatherling.one/eventreport.php?event=APAC Penny Dreadful Sundays 7.03', 'https://gatherling.one/eventreport.php?event=APAC Penny Dreadful Sundays 7.06', 'https://gatherling.one/eventreport.php?event=APAC Penny Dreadful Sundays 7.07', 'https://gatherling.one/eventreport.php?event=APAC Penny Dreadful Sundays 7.09', 'https://gatherling.one/eventreport.php?event=APAC Penny Dreadful Sundays 7.10', 'https://gatherling.one/eventreport.php?event=Penny Dreadful FNM - EU 7.02', 'https://gatherling.one/eventreport.php?event=Penny Dreadful FNM - EU 7.04', 'https://gatherling.one/eventreport.php?event=Penny Dreadful Mondays', 'https://gatherling.one/eventreport.php?event=Penny Dreadful Mondays 1.03', 'https://gatherling.one/eventreport.php?event=Penny Dreadful Mondays 1.04', 'https://gatherling.one/eventreport.php?event=Penny Dreadful Mondays 1.05', 'https://gatherling.one/eventreport.php?event=Penny Dreadful Mondays 1.06', 'https://gatherling.one/eventreport.php?event=Penny Dreadful Mondays 2.02', 'https://gatherling.one/eventreport.php?event=Penny Dreadful Mondays 6.13', 'https://gatherling.one/eventreport.php?event=Penny Dreadful Mondays 7.07', 'https://gatherling.one/eventreport.php?event=Penny Dreadful Mondays 7.08', 'https://gatherling.one/eventreport.php?event=Penny Dreadful Saturdays 6.04', 'https://gatherling.one/eventreport.php?event=Penny Dreadful Saturdays 6.05', 'https://gatherling.one/eventreport.php?event=Penny Dreadful Saturdays 6.08', 'https://gatherling.one/eventreport.php?event=Penny Dreadful Saturdays 6.09', 'https://gatherling.one/eventreport.php?event=Penny Dreadful Saturdays 6.10', 'https://gatherling.one/eventreport.php?event=Penny Dreadful Sundays 1.01', 'https://gatherling.one/eventreport.php?event=Penny Dreadful Sundays 1.06', 'https://gatherling.one/eventreport.php?event=Penny Dreadful Sundays 1.07', 'https://gatherling.one/eventreport.php?event=Penny Dreadful Sundays 1.08', 'https://gatherling.one/eventreport.php?event=Penny Dreadful Sundays 6.11', 'https://gatherling.one/eventreport.php?event=Penny Dreadful Sundays 6.12', 'https://gatherling.one/eventreport.php?event=Penny Dreadful Sundays 6.14', 'https://gatherling.one/eventreport.php?event=Penny Dreadful Sundays 6.16', 'https://gatherling.one/eventreport.php?event=Penny Dreadful Sundays 7.11', 'https://gatherling.one/eventreport.php?event=Penny Dreadful Sundays 7.12', 'https://gatherling.one/eventreport.php?event=Penny Dreadful Thursdays 6.07', 'https://gatherling.one/eventreport.php?event=Penny Dreadful Thursdays 6.08', 'https://gatherling.one/eventreport.php?event=Penny Dreadful Thursdays 6.11', 'https://gatherling.one/eventreport.php?event=Penny Dreadful Thursdays 7.12', 'https://gatherling.one/eventreport.php?event=Penny Paradise 1.11');

-- Tournaments with less than 8 players or that went wrong or are for demo purposes.
UPDATE competition SET top_n = 0 WHERE url IN ('https://gatherling.one/eventreport.php?event=APAC Penny Dreadful Sundays 7.08', 'https://gatherling.one/eventreport.php?event=Random Event For Video', 'https://gatherling.one/eventreport.php?event=Penny Dreadful FNM - EU 7.03', 'https://gatherling.one/eventreport.php?event=Penny Dreadful Sundays 1.128', 'https://gatherling.one/eventreport.php?event=Penny Dreadful Sundays 2.128', 'https://gatherling.one/eventreport.php?event=Penny Dreadful Sundays 2.129', 'https://gatherling.one/eventreport.php?event=Penny Dreadful Thursdays 0.00', 'https://gatherling.one/eventreport.php?event=Penny Dreadful Thursdays 2.07', 'https://gatherling.one/eventreport.php?event=Penny Dreadful Thursdays 2.11', 'https://gatherling.one/eventreport.php?event=Penny Paradise 0.01', 'https://gatherling.one/eventreport.php?event=Penny Paradise 0.03', 'https://gatherling.one/eventreport.php?event=Penny Paradise 0.05', 'https://gatherling.one/eventreport.php?event=Penny Paradise 0.06', 'https://gatherling.one/eventreport.php?event=Penny Paradise 1.07', 'https://gatherling.one/eventreport.php?event=Penny Paradise 1.16', 'https://gatherling.one/eventreport.php?event=Penny Paradise 2.06');

ALTER TABLE competition CHANGE COLUMN top_n top_n INTEGER NOT NULL;
