CREATE TABLE IF NOT EXISTS rule (
  id INTEGER PRIMARY KEY AUTO_INCREMENT,
  archetype_id INTEGER NOT NULL,
  FOREIGN KEY(archetype_id) REFERENCES archetype(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS rule_card (
  id INTEGER PRIMARY KEY AUTO_INCREMENT,
  rule_id INTEGER NOT NULL,
  card VARCHAR(100) NOT NULL,
  include INTEGER NOT NULL,
  FOREIGN KEY(rule_id) REFERENCES rule(id) ON DELETE CASCADE
);
