# make_stub_files: Sun 31 Dec 2017 at 16:46:32
from typing import Any, Dict
from shared.database_generic import GenericDatabase

class SqliteDatabase(GenericDatabase):
    def __init__(self, location: Any) -> None: ...
    def execute(self, sql: Any, args: Any=None) -> Any: ...
        #   0: return result.fetchall()
        # ? 0: return result.fetchall()
        #   1: return self.cursor.execute(sql,args).fetchall()
        # ? 1: return self.cursor.execute(sql, args).fetchall()
    def insert(self, sql: Any, args: Any=None) -> Any: ...
        #   0: return self.value('SELECT last_insert_rowid()')
        # ? 0: return self.value(str)
    def begin(self) -> None: ...
    def commit(self) -> None: ...
    def last_insert_rowid(self) -> Any: ...
        #   0: return self.value('SELECT last_insert_rowid()')
        # ? 0: return self.value(str)
    def concat(self, parts: Any) -> Any: ...
        #   0: return ' || '.join(parts)
        # ? 0: return str.join(parts)
    def is_sqlite(self) -> bool: ...
def row_factory(cursor: Any, row: Any) -> Dict[Any, Any]: ...
