# make_stub_files: Sun 31 Dec 2017 at 16:46:32
from shared.database_generic import GenericDatabase 
def location() -> str: ...
    #   0: return '{scratch_dir}/tmp.sqlite'.format(scratch_dir=configuration.get('scratch_dir'))
    # ? 0: return str.format(scratch_dir=configuration.get(str))
def setup() -> GenericDatabase: ...
    #   0: return db
    # ? 0: return db
def teardown_function() -> None: ...
def test_db() -> None: ...
def test_transaction() -> None: ...
def test_value() -> None: ...
def test_values() -> None: ...
def test_insert() -> None: ...
def test_sqlescape() -> None: ...
def test_sqllikeescape() -> None: ...
