# make_stub_files: Sun 31 Dec 2017 at 16:46:32
from typing import Any
from shared.database_generic import GenericDatabase

class MysqlDatabase(GenericDatabase):
    def __init__(self, db: Any) -> None: ...
    def begin(self) -> None: ...
    def commit(self) -> None: ...
    def last_insert_rowid(self) -> Any: ...
        #   0: return self.value('SELECT LAST_INSERT_ID()')
        # ? 0: return self.value(str)
    def concat(self, parts: Any) -> str: ...
    def is_mysql(self) -> bool: ...
    def supports_lock(self) -> bool: ...
    def get_lock(self, lock_id: Any, timeout: int=4) -> None: ...
    def release_lock(self, lock_id: Any) -> None: ...
