# make_stub_files: Sun 31 Dec 2017 at 16:46:32
def test_ts2dt() -> None: ...
def test_dt2ts() -> None: ...
def test_end_to_end() -> None: ...
def test_parse() -> None: ...
def test_parse_to_ts() -> None: ...
def test_now() -> None: ...
def test_display_date() -> None: ...
def test_rounding() -> None: ...
def test_display_time() -> None: ...
