name: Run mypy
on: ['push', 'pull_request']

jobs:
  build:
    name: mypy
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2.3.2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2.1.4
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip pipenv wheel
        if [ -f Pipfile ]; then pipenv sync; fi
    - name: Run mypy
      run: pipenv run python dev.py mypy
